### ISSUE TITLE
#include <cstring> for memset/memcpy

### ISSUE THREAD

**Issue by sagamusix** [leethomason/MicroPather#14]
`micropather.h` contains some function implementations which reference `memset` and `memcpy`, which are defined in `<cstring>`. This header is not included, so it is currently up to the library user to include it, whether they need it or not. The header should be included in `micropather.h` or the function implementations should be moved to `micropather.cpp`.

**Comment by leethomason** [comment]
Any chance you could post a PR?

**Comment by sagamusix** [comment]
For the simple inclusion of `<cstring>` I could do that, but I didn't do so far since I wanted to hear your opinion on moving those functions to `micropather.cpp` instead.

**Comment by leethomason** [comment]
Oops, sorry, dropped the thread. Probably better to move it to the cpp and include it from there.
