### ISSUE TITLE
Diagonal movement through obstacles?

### ISSUE THREAD

**Issue by MrJookie** [leethomason/MicroPather#5]
Hello, I've been playing around with MicroPather and would like to thank you for very nice lightweight "lib" :) 
It works supreme, just one problem: my path is going diagonally through obstacles. Did I miss something in the API? If not, what is the easiest workaround? I do not want to raise diagonal movement cost if possible.
![diagonal_movement](https://cloud.githubusercontent.com/assets/8093682/7892053/e1183d94-0651-11e5-967a-793971c58674.png)

**Comment by quiasmo** [comment]
Such physical obstacles aren't a concept that exists in Micropather.
If you have 8 neighbors per tile, Micropather is doing its job correctly.
You probably have to rethink what you graph means, or maybe use a line rasterization algorithm to make your obstacles thick.

**Comment by MrJookie** [comment]
Indeed it is, but I did not understand how to avoid cutting corners as written here http://www.policyalmanac.org/games/aStarTutorial.htm fig6 or fig7; I tried to add it, but somehow it messed up :D

**Comment by MrJookie** [comment]
Looks like I've solved it. Not sure, if it is right solution, but looks like it works.

	void Grid::AdjacentCost(void* node, micropather::MPVector<micropather::StateCost>* neighbors)
	{
		int x, y;
		const int dx[8] = { 1, 1, 0, -1, -1, -1, 0, 1 };
		const int dy[8] = { 0, 1, 1, 1, 0, -1, -1, -1 };
		const int cost[8] = { 10, 14, 10, 14, 10, 14, 10, 14 };

		NodeToXY(node, &x, &y);

		for (int i = 0; i < 8; ++i) {
			int nx = x + dx[i];
			int ny = y + dy[i];

			if (Passable(nx, ny)) {
				switch (i)
				{
				case 1:
					//std::cout << "diagonal down left" << std::endl;
					if (Passable(nx - 1, ny) || Passable(nx, ny - 1))
					{
						micropather::StateCost nodeCost = { XYToNode(nx, ny), cost[i] };
						neighbors->push_back(nodeCost);
					}
					break;

				case 3:
					//std::cout << "diagonal down left" << std::endl;
					if (Passable(nx + 1, ny) || Passable(nx, ny - 1))
					{
						micropather::StateCost nodeCost = { XYToNode(nx, ny), cost[i] };
						neighbors->push_back(nodeCost);
					}
					break;

				case 5:
					//std::cout << "diagonal up left" << std::endl;
					if (Passable(nx + 1, ny) || Passable(nx, ny + 1))
					{
						micropather::StateCost nodeCost = { XYToNode(nx, ny), cost[i] };
						neighbors->push_back(nodeCost);
					}
					break;

				case 7:
					//std::cout << "diagonal up right" << std::endl;
					if (Passable(nx - 1, ny) || Passable(nx, ny + 1))
					{
						micropather::StateCost nodeCost = { XYToNode(nx, ny), cost[i] };
						neighbors->push_back(nodeCost);
					}
					break;

				default:
					{
						micropather::StateCost nodeCost = { XYToNode(nx, ny), cost[i] };
						neighbors->push_back(nodeCost);
					}
					break;
				}
			}
		}
	}

**Comment by leethomason** [comment]
I haven't read the code in detail, but the shape of it looks correct: for NE to be passable, both N and E must be passable. I've written that code many times. It's one of the fiddly downsides of using squares for pathing. (Triangles and hexes have different fiddly downsides.)

**Comment by MrJookie** [comment]
Thx for the message, I think the issue can be closed.
