### ISSUE TITLE
Don't call raw interrupt routines

### ISSUE THREAD

**Issue by jtgans** [leethomason/MicroPather#6]
In the process of integrating your code into one of our projects, we noticed you were directly calling interrupt 3 on MSVC debug builds. This is dangerous -- just use assert, or allow for the calling application to override the definition of assert outside of your header. Assembler interrupts should be reserved for operating system libraries.

**Comment by jtgans** [comment]
Pull request #7 fixes this.

**Comment by leethomason** [comment]
Closing because there is an open PR to address.
